import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Box } from "@mui/material";
import { AllProviders } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Box
        component={"body"}
        sx={{
          maxWidth: "100vw",
          overflowX: "hidden",
        }}
      >
        <AllProviders>{children}</AllProviders>
      </Box>
    </html>
  );
}
